version: '2'
services:
  web:
    build: .
    volumes:
     - /uploads:/web/uploads
     - $PWD:/web
    links:
      - mongo
      - memcached
  mongo:
    image: "mongo:3.4.1"
  memcached:
    image: "memcached:1.4.34-alpine"
  nginx:
    image: "nginx:1.10.2-alpine"
    volumes:
      -  $PWD/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /root/logs/:/var/log/nginx/
    ports:
      - 80:80
    links:
      - web
